### PR TITLE
Taco epidemic

### PR DESCRIPTION
**Pull request by Aceba1**
Moves the necessary files out of the folder in the Installer directory to follow up with the recent merge; The sub-folder's contents are not required, as post-compilation copies files directly to the Installer directory.
To continue with that, this also moves some dependencies to the contents of the Installer directory. Such as the CommandLine.dll, and Mono.Cecil.dll.

Also replaces Oculus.Newtonsoft.Json with just Newtonsoft.Json. The one use by the game, that is. It shouldn't make a difference functionality-wise.

Modified the installation process a bit as well...

### CODE REVIEW

**Comment by Aceba1** [comment]
_I don't know what I'm doing_

**Comment by AlexejheroYTB** [comment]
This looks fairly good to me, I will make some small changes them merge

**Comment by AlexejheroYTB** [comment]
For future pull request, please briefly describe the changes in the title

**Comment by Aceba1** [comment]
I'll remember that for next time, thank you

**Pull request merged**
